services:
  neo4j:
    image: neo4j:2025.06.2-community-bullseye
    container_name: neo4j
    ports:
      - "${NEO4J_HOST_HTTP_PORT}:7474" # HTTP
      - "${NEO4J_HOST_BOLT_PORT}:7687" # Bolt protocol
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      neo4j:
        condition: service_healthy
      postgres:
        condition: service_healthy

    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=${NEO4J_USERNAME}
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=${NEO4J_PASSWORD}

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fluentLift
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

      - SECURITY_JWT_SECRET=${SECURITY_JWT_SECRET}
      - SECURITY_JWT_EXPIRATION=${SECURITY_JWT_EXPIRATION}

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: fluentLift
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USERNAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

volumes:
  neo4j-data:
  postgres-data:
